language: csharp 
dist: xenial

dotnet: 3.0.100
script: 
  - dotnet restore ./src/
  - dotnet build ./src/
  - dotnet test ./src/NHibernate.Caches.StackExchange.Redis.Tests
services:
  - redis 
branches:
  only: 
    - master
