image: Visual Studio 2019
install:
  - choco install redis-64
configuration: Release
before_build:
  - redis-server --service-install
  - redis-server --service-start
  - dotnet restore .\src\NHibernate.Caches.StackExchange.Redis.sln
build:
  project: .\src\NHibernate.Caches.StackExchange.Redis.sln
  verbosity: minimal
  publish_nuget: false
environment:
  REDIS_ADDR: "localhost"
  REDIS_PORT: 6379  
branches:
  only: 
    - master
