image: Visual Studio 2019
install:
  - choco install redis-64
configuration: Release
before_build:
  - dotnet restore .\src\NHibernate.Caches.StackExchange.Redis.sln
build:
  project: .\src\NHibernate.Caches.StackExchange.Redis.sln
  verbosity: minimal
  publish_nuget: false
